github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addComment: true
    addBadge: true
    addLabel: prebuilt-in-gitpod
vscode:
  extensions:
    - esbenp.prettier-vscode@2.3.0:1F0Pvb/ORZ/T+b60LIMs8w==
    - eamodio.gitlens@10.2.0:GNDO73Cmp0fYDiLNxVkbsQ==
